# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_auto_20171118_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='device',
            field=models.CharField(max_length=90),
        ),
    ]
